### ISSUE TITLE
TypeError JsonRpcSigner

### ISSUE THREAD

**Issue by mktcode** [PaulRBerg/hardhat-template#186]
I just installed bun for the first time to follow the readme here. On any hardhat related commands it seems, I get this: 

```
❯ bunx hardhat vars setup
There is an error in your Hardhat configuration file. Please double check it.

An unexpected error occurred:

TypeError: Cannot read properties of undefined (reading 'JsonRpcSigner')
    at Object.<anonymous> (/home/mkt/Projects/snapshot/multicall/node_modules/zksync-web3/build/src/signer.js:78:74)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .js] (/home/mkt/Projects/snapshot/multicall/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/mkt/Projects/snapshot/multicall/node_modules/zksync-web3/build/src/utils.js:20:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
```    

I removed node_modules, installed via npm and it works.

OS: Debian 12
node: 18.17.0
npm: 9.6.7
bun: 1.0.23

**Comment by PaulRBerg** [comment]
Thanks for reporting.

`bunx hardhat vars setup` works on my end - could you please confirm what OS you are using, and what Node.js version you have?

I would be happy to move this template to `npm`.

**Comment by PaulRBerg** [comment]
Silly question but have you run `bun install` before running `bunx hardhat vars setup`?

**Comment by PaulRBerg** [comment]
Got it. That's a shame.

Would you be able to make a PR that replaces bun with npm?

**Comment by PaulRBerg** [comment]
Don't think it's related

**Comment by njelich** [comment]
@PaulRBerg I think it might be related, I get this error on `bun run compile`:

```
TypeError: Cannot read properties of undefined (reading 'JsonRpcSigner')
    at Object.<anonymous> (/home/noah/yieldb/smart-contracts/node_modules/zksync-web3/build/src/signer.js:78:74)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.require.extensions.<computed> [as .js] (/home/noah/yieldb/smart-contracts/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/noah/yieldb/smart-contracts/node_modules/zksync-web3/build/src/utils.js:20:18)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
error: script "compile" exited with code 1
```

And you can see that zksync-web3 is in the backtrace.

Taking a look at the CI, and noting that there are no real code changes between this and the last run, there was obviously a change in one of the dependencies. zksync-web3 is a dependency of hardhat-deploy, so would be a good idea to start tracking there.
